robot:
  robot_ip: '192.168.58.2'
  robot_name: 'NRMK-Indy7'
  cali: [[0, 1, 0],
        [1, 0, 0],
        [0, 0, -1],
        [-0.13, 0, 0]]
  endtoolcart: 0
  vel: 15
  offset: -0.6
  
vision:
  camera: 'AK'
  camwidth: 1920
  model: 'detectron2'
  class_name: ['cup_label']